### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by GerryT11** [nE0sIghT/ReminderAlarmClock#2]
Hi @nE0sIghT , Gnome 46 is out and ReminderAlarmClock does not yet support it. Thanks.

**Comment by nE0sIghT** [comment]
Hi!

Does it works for you with `disable-extension-version-validation`?

**Comment by GerryT11** [comment]
Thanks, I tried it with disabled extension version validation, but it shows "error" after installation. Unfortunately, it does not work.

**Comment by elcaos** [comment]
Same here. I'm getting the message: `TypeError: oneBox.add is not a function`.

**Comment by nE0sIghT** [comment]
> Same here. I'm getting the message: "TypeError: oneBox.add is not a function".

Is it the only error from extension?

**Comment by elcaos** [comment]
It is the only error I can find. It shows up when I'm opening the Extensions Settings GUI. I can't find anything in my logs.

![grafik](https://github.com/nE0sIghT/ReminderAlarmClock/assets/16786660/8f658083-238a-4f98-8220-58ce51e3840e)

Unfortunately, I can't take a screenshot of the dialogue that opens when clicking on the "x", but it gives the exact error message mentioned above.

**Comment by nE0sIghT** [comment]
Please try fix from https://github.com/nE0sIghT/ReminderAlarmClock/pull/3

Since there is still no GNOME-46 in the Gentoo I cann't test it

**Comment by elcaos** [comment]
This resolved the first problem. Now, as a follow-up, I get `TypeError: menuItem.actor.add is not a function`. Since I don't know a better way I need to restart my PC each time to activate the changes. Simply deactivating/activating the plugin doesn't do the trick. I now updated the current error as well with "add_child" and will reboot to see if it fixes everything.

**Comment by elcaos** [comment]
Ok, this now fixes most of it, but the pop-up won't show up. In my logs, I now get the error: `TypeError: Main.uiGroup.add_actor is not a function#012_showReminderWithCloseButton`

**Comment by nE0sIghT** [comment]
I updated PR - please test if it fixes issues for you

**Comment by elcaos** [comment]
Good morning nE0sIghT, now it's working again. Thank you so much for helping at such short notice. Your alarm clock tool is just awesome, and I use it every day. Thanks again man, I truly appreciate it!

**Comment by GerryT11** [comment]
Hi nE0sIghT: Thanks for the update. The new version works nicely on my computer (Gnome 46, Ubuntu 24.04).
