### ISSUE TITLE
Displaced tiles

### ISSUE THREAD

**Issue by sojusnik** [nE0sIghT/ReminderAlarmClock#5]
In Ubuntu 24.04 with Gnome 46.1 and the default Gnome-Shell theme, the tiles of the right column are displaced, although they were properly aligned in Ubuntu 23.10 with Gnome 45, see:

![image](https://github.com/nE0sIghT/ReminderAlarmClock/assets/1245718/93fa1999-fab0-47dc-8485-7c9da1d65525)

Do you observe this with other themes as well?

**Comment by nE0sIghT** [comment]
I'm still use GNOME 45 so can not test it yet

**Comment by nE0sIghT** [comment]
I just uploaded new version to ego which should fix this issue
